apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-for-cert-manager
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-wait-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for cert-manager CRDs..."
          for crd in certificates.cert-manager.io clusterissuers.cert-manager.io issuers.cert-manager.io; do
            until kubectl get crd $crd >/dev/null 2>&1; do
              echo "Waiting for $crd..."
              sleep 5
            done
            echo "$crd is ready"
          done
          
          echo "Waiting for cert-manager pods to be ready..."
          kubectl wait --for=condition=ready pod \
            -l app.kubernetes.io/instance=cert-manager \
            -n cert-manager \
            --timeout=300s
          
          echo "Waiting for cert-manager webhook to be ready..."
          kubectl wait --for=condition=ready pod \
            -l app.kubernetes.io/component=webhook \
            -n cert-manager \
            --timeout=300s
          
          echo "cert-manager is fully ready!"
      restartPolicy: Never
  backoffLimit: 3