apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
  - list:
      items:
      - name: api-service
        valuesFile: "values/api-service.yaml"  # ← INSIDE app-helmchart
      - name: front-service
        valuesFile: "values/front-service.yaml"  # ← INSIDE app-helmchart
      - name: option-service
        valuesFile: "values/option-service.yaml"  # ← INSIDE app-helmchart
  
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/HassanTariqAlvi/Helm-Microservice-Argocd.git
        targetRevision: main
        path: app-helmchart
        helm:
          valueFiles:
          - '{{valuesFile}}'  # This resolves to "values/api-service.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
