# argocd-apps-of-apps/apps-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: api-service
          valuesFile: "values/api-service.yaml"
        - name: front-service
          valuesFile: "values/front-service.yaml"
        - name: option-service
          valuesFile: "values/option-service.yaml"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/HassanTariqAlvi/Helm-Microservice-Argocd.git
        targetRevision: main
        path: app-helmchart
        helm:
          valueFiles:
          - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
